# yaml 配置实例
version: '3'
name: "stock"
services:
  mysql:
    image: "docker.cnb.cool/php127/docker/mysql:8.4.3-oracle"
    ports:
      - "3307:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/log:/var/log/"
      - "./mysql/my.cnf:/etc/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Shanghai"
    restart: always
    privileged: true
    networks:
      - stock_network
  redis:
    image: "registry.cn-hangzhou.aliyuncs.com/php127/redis:6.2.5"
#    ports:
#      - "6379:6379"
    volumes:
      - "./redis/data:/data/redis/data"
      - "./redis/redis.conf:/etc/redis.conf"
    command: "redis-server /etc/redis.conf"
    restart: always
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - stock_network
  php:
    image: "docker.cnb.cool/php127/docker/php:8.4-cli-alpine"
    restart: always
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - stock_network
    ports:
      - "8018:8018"
    volumes:
      - "../:/www/"
      - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    command: ["sh","/www/docker/run.sh"]
networks:
  stock_network:
    driver: bridge

